module.exports = [
	{
		id: 3,
		make: 'roland',
		model: 'jupiter',
		year: '1984',
		polyphony: '6',
		hardware: true,
		software: false,
		kybrd: true,
		module: false,
		rack: false,
		desktop: false,
		workstation: false,
		grooveBox: false,
		sampler: false,
		sequencer: false,
		arpeggiator: true,
		multitimbral: true,
		midi:false,
		dinsync:true,
		img: 'https://www.rolandus.com/blog/wp-content/uploads/2013/02/1981-JUPITER-8.png',
		text:"The Jupiter-8 was Roland's flagship synthesizer for the first half of the 1980s. "
	},
	{
		id: 1,
		make: 'sofwareSynth',
		model: 'sofware',
		year: '1999',
		polyphony: '64',
		hardware: false,
		software: true,
		kybrd: false,
		module: false,
		rack: false,
		desktop: false,
		workstation: false,
		grooveBox: false,
		sampler: false,
		sequencer: false,
		arpeggiator: true,
		multitimbral: true,
		midi:true,
		dinsync:false,
		img: 'https://upload.wikimedia.org/wikipedia/en/6/69/FL_Studio_11_just_logo.png',
		text: "The Jupiter-8 was Roland's flagship synthesizer for the first half of the 1980s. Although it lacked the soon-to-be standard of MIDI control, "
	},
	{
		id: 2,
		make: 'korg',
		model: 'esx-1',
		year: '2000',
		polyphony: '2',
		hardware: true,
		software: false,
		kybrd: true,
		module: false,
		rack: false,
		desktop: true,
		workstation: false,
		grooveBox: true,
		sampler: true,
		sequencer: true,
		arpeggiator: true,
		multitimbral: true,
		midi:true,
		dinsync:false,
		img: 'http://www.vintagesynth.com/sites/default/files/2017-05/esx1.jpg',
		text:"The ELECTRIBE SX is a major step up in power and quality from the original ElecTribe series of dance music sequencer/synthesizers from Korg. The ESX-1 comes in a sturdy metal chassis with larger back-lit LCD display, expanded memory, voices & multitimbrality, more real-time controllers and vacuum tubes! Effects, Motion Sequencing, and Pattern length have also been expanded. And a new ribbon controller and slider have been added, providing a remarkable realtime interface for accessing the powerful arpeggiator."
	},
	{
		id: 4,
		make: 'yamaha',
		model: 'dx7',
		year: '1987',
		polyphony: '12',
		hardware: true,
		software: false,
		kybrd: true,
		module: false,
		rack: false,
		desktop: false,
		workstation: false,
		grooveBox: false,
		sampler: false,
		sequencer: false,
		arpeggiator: false,
		multitimbral: false,
		_frequency_modulation:true,
		midi:true,
		dinsync:false,
		img: 'https://upload.wikimedia.org/wikipedia/commons/0/03/YAMAHA_DX7.jpg',
		text: "The Yamaha DX7 is a synthesizer manufactured by the Yamaha Corporation from 1983 to 1989. It was the first commercially successful digital synthesizer, and is one of the bestselling synthesizers in history, selling over 200,000 units.In the early 1980s, the synthesizer market was dominated by analog synthesizers. Frequency modulation (FM) synthesis, a means of generating sounds digitally with different results, was developed by John Chowning at Stanford University, California. Yamaha licensed the technology to create the DX7, combining it with very-large-scale integration chips to lower manufacturing costs."
	},
	{
		id: 5,
		make: 'yamaha',
		model: 'tx81z',
		year: '1987',
		polyphony: '12',
		hardware: true,
		software: false,
		kybrd: false,
		module: false,
		rack: true,
		desktop: false,
		workstation: false,
		grooveBox: false,
		sampler: false,
		sequencer: false,
		arpeggiator: false,
		multitimbral: true,
		_frequency_modulation: true,
		midi:true,
		dinsync:false,
		img: 'http://www.vintagesynth.com/sites/default/files/2017-05/yamaha_tx81z.jpg'
	},
	{
		id: 5,
		make: 'yamaha',
		model: 'tx81z software',
		year: '2987',
		polyphony: '12',
		hardware: false,
		software: true,
		kybrd: false,
		module: false,
		rack: false,
		desktop: false,
		workstation: false,
		grooveBox: false,
		sampler: false,
		sequencer: false,
		arpeggiator: false,
		multitimbral: true,
		midi:true,
		dinsync:false,
		img: 'http://www.vintagesynth.com/sites/default/files/2017-05/yamaha_tx81z.jpg'
	}
]